apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-k8s-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-k8s-deployment    
  template:
    metadata:
      labels:
        app: node-k8s-deployment
    spec:
      containers:
      - name: node-k8s-deployment
        image: mikenandi/node-k8:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
