apiVersion: v1
kind: Service
metadata:
  name: k8s-web
spec:
  type: LoadBalancer
  selector:
    app: k8s-web
  ports:
  - port: 3030
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web    
  template:
    metadata:
      labels:
        app: k8s-web
    spec:
      containers:
      - name: k8s-web
        image: mikenandi/node-k8:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
